name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g pnpm
      - run: pnpm install
      - run: npm run build --if-present
      - run: npm run pub2 --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
